# Auto-generated by code_generator for scenario: skew_on_join_30x
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, rand, when

spark = (SparkSession.builder.appName("skew_on_join_30x")
    .config("spark.sql.adaptive.enabled", "true")
    .config("spark.sql.adaptive.skewJoin.enabled", "false")
    .config("spark.sql.autoBroadcastJoinThreshold", "-1")
    .config("spark.sql.shuffle.partitions", "8")
    .getOrCreate())

# Gerar dados de exemplo conforme o scenario.yaml
orders = spark.range(200000).select(
    (rand(42) * 100).cast('int').alias('customer_id'),
    col('id').alias('order_id')
)
# Injetar hot key
orders = orders.withColumn(
    'customer_id',
    when(rand(13) < 0.8, 7)
    .otherwise(col('customer_id'))
)

customers = spark.range(100).select(
    col('id').alias('customer_id'),
    col('id').alias('customer_name')
)

# >>> ANTI-PATTERN LINE 58 - skew join <<<
result = orders.join(customers, "customer_id", "inner")

result.write.mode("overwrite").parquet("/tmp/apex_output")
result.show(10)
spark.stop()
