#!/usr/bin/env python3
import yaml
import sys

def generate_job(scenario_path, output_path):
    with open(scenario_path, 'r') as f:
        config = yaml.safe_load(f)

    scenario_id = config['scenario_id']
    code_cfg = config['code_generator']
    anti_pattern_line = code_cfg['anti_pattern_line']
    data = code_cfg['data']
    spark_conf = code_cfg.get('spark_config', {})

    config_lines = ''.join([f'    .config("{k}", "{v}")\n' for k, v in spark_conf.items()])

    template = f'''# Auto-generated by code_generator for scenario: {scenario_id}
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, rand, when

spark = (SparkSession.builder.appName("{scenario_id}")
{config_lines}    .getOrCreate())

# Gerar dados de exemplo conforme o scenario.yaml
orders = spark.range({data['orders']['rows']}).select(
    (rand(42) * {data['orders']['distinct_keys']}).cast('int').alias('customer_id'),
    col('id').alias('order_id')
)
# Injetar hot key
orders = orders.withColumn(
    'customer_id',
    when(rand(13) < {data['orders']['hot_share']}, {data['orders']['hot_key']})
    .otherwise(col('customer_id'))
)

customers = spark.range({data['customers']['rows']}).select(
    col('id').alias('customer_id'),
    col('id').alias('customer_name')
)

# >>> ANTI-PATTERN LINE {anti_pattern_line} - skew join <<<
result = orders.join(customers, "customer_id", "inner")

result.write.mode("overwrite").parquet("/tmp/apex_output")
result.show(10)
spark.stop()
'''
    with open(output_path, 'w') as f:
        f.write(template)
    print(f"✅ Gerado {output_path} a partir de {scenario_path}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Uso: python code_generator.py <scenario.yaml> <output_job.py>")
        sys.exit(1)
    generate_job(sys.argv[1], sys.argv[2])
